export const GET_UNIVERSITIES_BEGIN = "GET_UNIVERSITIES_BEGIN";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAILURE = "GET_UNIVERSITIES_FAILURE";

export const SET_EDUCATION_DETAILS = "SET_EDUCATION_DETAILS";
