export const GET_UNIVERCITIES_BEGIN = "GET_UNIVERCITIES_BEGIN";
export const GET_UNIVERCITIES_SUCCESS = "GET_UNIVERCITIES_SUCCESS";
export const GET_UNIVERCITIES_FAILURE = "GET_UNIVERCITIES_FAILURE";
